DAVIDTypeChoices <- strsplit(
"AFFY_ID
ENTREZ_GENE_ID
GENBANK_ACCESSION
GENPEPT_ACCESSION
GI_ACCESSION
PIR_ACCESSION
PIR_ID
PIR_NREF_ID
REFSEQ_GENOMIC
REFSEQ_MRNA
REFSEQ_PROTEIN
REFSEQ_RNA
UNIGENE
UNIPROT_ACCESSION
UNIPROT_ID
UNIREF100_ID
OFFICIAL_GENE_SYMBOL", split="\n")[[1]]
